linters:
  enable-all: true
  disable:
    - gofumpt
    - varcheck
    - nosnakecase
    - interfacer
    - scopelint
    - exhaustivestruct
    - maligned
    - structcheck
    - ifshort
    - deadcode
    - golint
    - depguard
    - wsl
    - wrapcheck
    - exhaustruct
    - varnamelen
    - tagliatelle
    - godox
    - copyloopvar
    - intrange

linters-settings:
  cyclop:
    max-complexity: 15
